# Netflix Movies & TV Shows — Exploratory Data Analysis
**CodeAlpha Data Analytics Internship — Task 2**

This notebook explores the Netflix titles dataset (8,807 entries) to uncover patterns in content type, country distribution, ratings, duration, and trends over time.

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("netflix_titles.csv")

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [5]:
df.shape

(8807, 12)

In [6]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [8]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

In [9]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [10]:
df = df.dropna(subset =['date_added'])

In [11]:
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [12]:
df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

In [13]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [14]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [15]:
df['date_added'] = pd.to_datetime(df['date_added'].str.strip())
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [16]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9

In [17]:
df['duration_int'] = df['duration'].str.extract(r'(\d+)').astype(int)
df['duration_type'] = df['duration'].apply(lambda x: 'Season' if 'Season' in x else 'Minute')

In [18]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,duration_int,duration_type
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,90,Minute
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,2,Season
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,1,Season
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,1,Season
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,2,Season

In [19]:
df.to_csv("netflix_cleaned.csv", index=False)

In [20]:
df[['duration', 'duration_int', 'duration_type', 'date_added', 'year_added', 'month_added']].head(10)

    duration  duration_int duration_type date_added  year_added  month_added
0     90 min            90        Minute 2021-09-25        2021            9
1  2 Seasons             2        Season 2021-09-24        2021            9
2   1 Season             1        Season 2021-09-24        2021            9
3   1 Season             1        Season 2021-09-24        2021            9
4  2 Seasons             2        Season 2021-09-24        2021            9
5   1 Season             1        Season 2021-09-24        2021            9
6     91 min            91        Minute 2021-09-24        2021            9
7    125 min           125        Minute 2021-09-24        2021            9
8  9 Seasons             9        Season 2021-09-24        2021            9
9    104 min           104        Minute 2021-09-24        2021            9

# Exploratory Data Analysis — Questions & Insights

Now that the dataset is cleaned, let's explore it by asking meaningful questions about 
content type, country distribution, ratings, duration, and trends over time.

## Q1: How many Movies vs TV Shows are there?

In [21]:
df['type'].value_counts()

type
Movie      6131
TV Show    2666
Name: count, dtype: int64

## Q2: What are the oldest and newest titles on Netflix?

In [22]:
df[['title','release_year']].sort_values('release_year').head(2)

                                  title  release_year
4250  Pioneers: First Women Filmmakers*          1925
8205               The Battle of Midway          1942

In [23]:
df[['title','release_year']].sort_values('release_year').tail(2)

                                              title  release_year
20  Monsters Inside: The 24 Faces of Billy Milligan          2021
23     Go! Go! Cory Carson: Chrissy Takes the Wheel          2021

## Q3: Which month do most titles get added to Netflix?

In [24]:
df['month_added'].value_counts().sort_index()

month_added
1     738
2     563
3     742
4     764
5     632
6     728
7     827
8     755
9     770
10    760
11    705
12    813
Name: count, dtype: int64

## Q4: What's the single longest movie on Netflix?

In [25]:
df[df['duration_type']=='Minute'].sort_values('duration_int', ascending=False)[['title','duration']].head(3)

                            title duration
4253   Black Mirror: Bandersnatch  312 min
717   Headspace: Unwind Your Mind  273 min
2491       The School of Mischief  253 min

## Q5: Which TV show has the most seasons?

In [26]:
df[df['duration_type']=='Season'].sort_values('duration_int', ascending=False)[['title','duration']].head(3)

               title    duration
548   Grey's Anatomy  17 Seasons
2423    Supernatural  15 Seasons
4798            NCIS  15 Seasons

## Q6: What's the longest title name on Netflix?

In [27]:
df['title_length'] = df['title'].apply(len)
df.sort_values('title_length', ascending=False)[['title']].head(3)

                                                  title
5164  Jim & Andy: The Great Beyond - Featuring a Ver...
2813  Ken Burns Presents: College Behind Bars: A Fil...
8462  The Power of Grayskull: The Definitive History...

## Q7: What percentage of total content is Movies vs TV Shows?

In [28]:
df['type'].value_counts(normalize=True) * 100

type
Movie      69.694214
TV Show    30.305786
Name: proportion, dtype: float64

## Q8. Which countries have the most content?

In [29]:
df['country'].value_counts().head(3)

country
United States    2812
India             972
Unknown           830
Name: count, dtype: int64

## Q9: What's the most common content rating overall?

In [30]:
df['rating'].value_counts().head(3)

rating
TV-MA    3209
TV-14    2157
TV-PG     861
Name: count, dtype: int64

## Q10: How many titles were added in the most recent year (2021) compared to the very first year in the data?

In [31]:
df['year_added'].value_counts().sort_index()[[df['year_added'].min(), df['year_added'].max()]]

year_added
2008       2
2021    1498
Name: count, dtype: int64

# Key Takeaways
- Movies dominate the catalog (~70%) though TV Shows have grown steadily
- Content skews mature (TV-MA is the top rating)
- The US and India lead in content volume, with ~9% of entries missing country data
- December and July are peak months for new content additions